<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="5.8130" tests="1" failures="1">
  <testsuite name="Root Suite" timestamp="2020-07-01T14:53:21" tests="0" file="cypress/integration/secondTest.spec.js" time="0.0000" failures="0">
  </testsuite>
  <testsuite name="Test log out" timestamp="2020-07-01T14:53:21" tests="1" time="5.8130" failures="1">
    <testcase name="Test log out verify you can log out successfully" time="5.8130" classname="verify you can log out successfully">
      <failure message="Timed out retrying: expected &apos;&lt;ul.nav.navbar-nav.pull-xs-right&gt;&apos; to contain &apos;Sign up1&apos;" type="AssertionError"><![CDATA[AssertionError: Timed out retrying: expected '<ul.nav.navbar-nav.pull-xs-right>' to contain 'Sign up1'
    at Context.eval (http://localhost:4200/__cypress/tests?p=cypress/integration/secondTest.spec.js:9:31)]]></failure>
    </testcase>
  </testsuite>
</testsuites>